# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruin < Formula
  desc "Bruin is a command-line tool for validating and running data transformations on SQL and Python."
  homepage "https://getbruin.com"
  version "0.11.86"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/bruin-data/bruin/releases/download/v0.11.86/bruin_Darwin_x86_64.tar.gz"
      sha256 "c73e7059105f9236ff231a2f7d0440b140863557e70873acf85375d83a37cff4"

      def install
        bin.install "bruin"
      end
    end
    on_arm do
      url "https://github.com/bruin-data/bruin/releases/download/v0.11.86/bruin_Darwin_arm64.tar.gz"
      sha256 "8852d97c5964cbe2af3d778a843b7b0035d81285dcf5849d9f437b34290e3846"

      def install
        bin.install "bruin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bruin-data/bruin/releases/download/v0.11.86/bruin_Linux_x86_64.tar.gz"
        sha256 "a303e4b248a64fdeedb544f1831f028ee9eaf4a9a429ba84c6ee7bac1ca43d2c"

        def install
          bin.install "bruin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bruin-data/bruin/releases/download/v0.11.86/bruin_Linux_arm64.tar.gz"
        sha256 "0670b22d3816e21ba57cfc29ce2ec0e71f93b6fa20f43f329b866459bb071525"

        def install
          bin.install "bruin"
        end
      end
    end
  end
end
